/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package lfl.centralbank;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;


/**
 *
 * @author Luisito
 */
public class BankComm { //implements Runnable{

    private Service bankService;
    /*private SerializableObject message_out;
    private SerializableObject message_in;*/

    private String message_out;
    private String message_in;

    public BankComm(){

    }

    public BankComm(Service bankService, String message_out){
        this.bankService = bankService;
        this.message_out = message_out;        

//        Thread t = new Thread(this);
//        t.start();
    }

    public Object getResponse() {

        try {

            /*
             * Connect to the server
             */

            //InetAddress host = InetAddress.getLocalHost();
            Socket socket = new Socket(bankService.getServiceIP(), bankService.getServicePort());

            /*
             * Send the input to the server. This contains the values randomly
             * generated by the generateInput() method.
             */
            //Message is received on server as a String
            //System.out.println("BankComm: message_out: " + message_out.getObject().toString());
            //System.out.println("BankComm: message_out: " + message_out);
            ObjectOutputStream o_str = new ObjectOutputStream(socket.getOutputStream());
            o_str.writeObject(message_out);

            /*
             * Get the result from the server and print it out on the console
             */
            ObjectInputStream i_str = new ObjectInputStream(socket.getInputStream());
            //Object myObject = i_str.readObject();
            //System.out.println("Setting message_in in BankComm!");
            //message_in.setObject(i_str.readObject());
            message_in = i_str.readObject().toString();
            //System.out.println("This is what the server responded: " + message_in.getObject().toString());
            //System.out.println("This is what the server responded: " + message_in);
            //System.out.println("Received from server: " + ((CustomerAccount)message_in.getObject()).toString());
            //System.out.println("Result: " + myObject.toString());

            /*
             * Close input and output streams
             */
            i_str.close();
            o_str.close();

            } catch (UnknownHostException e) {
              e.printStackTrace();
            } catch (IOException e) {
              e.printStackTrace();
            } catch (ClassNotFoundException e) {
              e.printStackTrace();
            }

        return message_in;
    }

    /*public SerializableObject getServerResponse(){
        System.out.println("Getting message_in from BankComm!");
        return message_in;
    }*/
}
